use orcadsystem;

INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0200','RES-SMD','RESISTOR','RES-SMD;value,tolerance,package,power','R<Package>_<Value><Unit>_<Power>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0210','RES-DIP','RESISTOR','RES-DIP;value,tolerance,package,power','R<Package>_<Value><Unit>_<Power>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0220','RES-VR','RESISTOR','RES-VR;value,tolerance,package,power','R<Package>_<Value><Unit>_<Power>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0230','RES-ARRAY','RESISTOR','RES-ARRAY;value,qty of res,package','R<Package>_<Value><Unit>_<Power>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0240','RES-SPECIAL','RESISTOR','RES-SPECIAL;value,tolerance,power,info','R<Package>_<Value><Unit>_<Power>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0301','CAP-CER,SMD','CAPACITOR','CAP-CER,SMD;value,tolerance,package,voltage,material','C<Package>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0302','CAP-TA,SMD','CAPACITOR','CAP-TA,SMD;value,tolerance,package,voltage,ESR','C<Type>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0303','CAP-ALUM,SMD','CAPACITOR','CAP-ALUM,SMD;Value,tolerance,Package,voltage,ESR','C<Type>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0304','CAP-EDL','CAPACITOR','CAP-EDL,SMD;Value,tolerance,Package,voltage,ESR','C<Type>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0306','CAP-CER,DIP','CAPACITOR','CAP-CER,DIP;value,tolerance,package,voltage,material','C<Package>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0307','CAP-TA,DIP','CAPACITOR','CAP-TA,DIP;value,tolerance,package,voltage,ESR','C<Type>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0308','CAP-ALUM,DIP','CAPACITOR','CAP-ALUM,DIP;Value,tolerance,Package,voltage,ESR','C<Type>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0309','CAP-ARRAY','CAPACITOR','CAP-ARRAY;valueXqty  of  C,tolerance,package,voltage','C<Type>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0305','CAP-MICA,SMD','CAPACITOR','CAP-MICA,SMD;value,voltage,tolerance,package','C<Type>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0310','CAP-MICA,DIP','CAPACITOR','CAP-MICA,DIP;value,tolerance,voltage,package','C<Type>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0311','CAP-OXI_NIOB,SMD','CAPACITOR','CAP-OXI_NIOB,SMD;value,tolerance,voltage','C<Type>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0312','CAP-VR,SMD','CAPACITOR','CAP-VR,SMD;value,voltage,tolerance,package','C<Type>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0313','CAP-VR,DIP','CAPACITOR','CAP-VR,DIP;value,voltage,tolerance,package','C<Type>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0314','CAP-THIN_FILM,SMD','CAPACITOR','CAP-THIN_FILM,SMD;value,voltage,info','C<Type>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0315','CAP-PAS,SMD','CAPACITOR','CAP-PAS,SMD;Value,voltage,ESR,package','C<Type>_<Value><Unit>_<Voltage>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0401','DIODE-SWITCHING','DIODE','DIODE-SWITCHING;voltage,current,package,mfg1_part#','DIO_<Part Number>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0404','DIODE-SCHOTTKY','DIODE','DIODE-SCHOTTKY;voltage,current,package,mfg1_part#','DIO_<Part Number>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0406','DIODE-ARRAY','DIODE','DIODE-ARRAY;voltage,current,package,mfg1_part#','DIO_<Part Number>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0402','DIODE-RECTIFIER','DIODE','DIODE-RECTIFIER;voltage     DC,current,package,mfg1_part#','DIO_<Part Number>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0405','BRIDGE','DIODE','BRIDGE;voltage,current,package,mfg1_part#','DIO_<Part Number>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0403','DIODE-ZENER','DIODE','DIODE-ZENER;voltage,power,package,mfg1_part#','DIO_<Part Number>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1100','LED-SMD','LED','LED-SMD;Voltage,Current,package,color','LED_<Part Number>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1101','LED-DIP','LED','LED-DIP;Voltage,Current,package,color','LED_<Part Number>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1102','LED-MATRIX','LED','LED-MATRIX; Configuration,Size,Colour, Voltage,Internal Connection','LED_<Part Number>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1103','LED-IR','LED','LED-IR;   Wavelength,Emitter/Receiver,Voltage,Current,Viewing   Angle,Package','LED_<Part Number>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1104','LED-7SEG','LED','LED-7SEG;Voltage,Current,package,color','LED_<Part Number>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0501','TRANS-BJT','TRANSISTOR','TRANS-BJT;type,voltage,current,package','<Part_Type>_<Sub type>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0502','TRANS-POWER','TRANSISTOR','TRANS-POWER;type,voltage,current,package','<Part_Type>_<Sub type>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0504','TRANS-DIGITAL','TRANSISTOR','TRANS-DIGITAL;type,voltage,current,package,R1/R2','<Part_Type>_<Sub type>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0505','MOS-FET','TRANSISTOR','MOS-FET;type,voltage,current,package','<Part_Type>_<Sub type>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0503','TRANS-BJT,ARRAY','TRANSISTOR','TRANS-BJT,ARRAY;NumberxType,voltage,current,package','<Part_Type>_<Sub type>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0506','TRANS-RF','TRANSISTOR','TRANS-RF;type, Voltage - Collector Emitter Breakdown,Power-Max,Frequency,package','<Part_Type>_<Sub type>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0507','JFET','TRANSISTOR','JFET;Type,Voltage Breakdown,Power – Max,package','<Part_Type>_<Sub type>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0508','RF-FET','TRANSISTOR','RF-FET;type,Frequency,Voltage – Rated, Current Rating,package','<Part_Type>_<Sub type>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0509','TRANS-BJT,ARRAY,Pre-Bias','TRANSISTOR','TRANS-BJT,ARRAY,Pre-Bias;type,voltage,current,package','<Part_Type>_<Sub type>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0510','TRANS-BJT,Pre-Bias','TRANSISTOR','TRANS-BJT,Pre-Bias;type,voltage,current,package','<Part_Type>_<Sub type>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0511','MOS-FET,ARRAY','TRANSISTOR','MOS-FET,ARRAY;type,voltage,current,package','<Part_Type>_<Sub type>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1300','CRYSTAL','OSCILLATOR','CRYSTAL;Freq,Tolerance,C_load,Package','XTAL_<Freq>_<P/N prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1301','OSCILLATOR','OSCILLATOR','OSCILLATOR;Frequency,tolerance,voltage,package','OSC_<Freq>_<P/N prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1600','CONN-SMD','CONNECTOR','CONN-SMD;name,package,info','CONN_<info>_<P/N prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1700','CONN-DIP','CONNECTOR','CONN-DIP;type,package,info','CONN_<Interface>_<P/N prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1200','FILTER-SMD','FILTER','FILTER;Type,package,info','<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1210','FILTER-DIP','FILTER','FILTER;Type,package,info','<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1400','VARACTOR','VARACTOR','VARACTOR;Value,Voltage,Package','VR_<Capacitance>@<Voltage>@<Freq>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1500','THERMISTOR','THERMISTOR','THERMISTOR;type,Value,package','RT_<Resistance>@<Temp>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2100','IND-SMD','INDUCTOR','IND-SMD;Value,tolerance,package,current,DCR','L<Package>_<Value><Unit>_<Current>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2140','IND-DIP','INDUCTOR','IND-DIP;Value,tolerance,package,current,DCR','L<Package>_<Value><Unit>_<Current>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2110','IND-DJ','INDUCTOR','IND-DJ; Inductance,Tolerance, Package','L<Package>_<Value><Unit>_<Current>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2120','IND-ARRAY','INDUCTOR','IND-ARRAY;Value,tolerance,package,current,DCR','L<Package>_<Value><Unit>_<Current>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2130','DELAY LINE','INDUCTOR','DELAY LINE;Value,tolerance,package,current,DCR','L<Package>_<Value><Unit>_<Current>_<Tolerance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2400','RELAY','RELAY','X','RL_<Control voltage<Unit>DC/AC');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2700','FUSE','FUSE','X','FUSE_<Trip current>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2710','FUSE-CLIP','FUSE','X','FUSE_<Trip current>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2720','FUSE-COVER','FUSE','X','FUSE_<Trip current>_<Package>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2800','ESD','ESD','ESD;Direction,Capacitance,Work   Voltage,Package','ESD_<P/N prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2810','TVS-DIODE','TVS','TVS-DIODE;Direction,Power,Protect    Voltage,Package','ESD_<P/N prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2820','TVS-HYRIST','TVS','TVS-HYRIST;Voltage–Breakover,Current - Peak Pulse,Package','ESD_<P/N prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2830','TVS-VARISTOR','TVS','TVS-VARISTOR;Direction,Power,Protect    Voltage,Package','ESD_<P/N prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('3000','MODULE','MODULE','X','X');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2900','FERRITE BEAD','FERRITE BEAD','FB;Value,Current,Package','FB<Package>_<Impedance>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2500','TRANSFORMER','TRANSFORMER','X','X');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0600','IC-CMOS LOGIC','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0710','IC-MICROPROCESSOR','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0720','IC-GRAPHIC CONT.','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0800','IC-ANALOG MULTIPLEX','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0810','IC-ANALOG SWITCH','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0820','IC-RF SWITCH','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0830','IC-LEVEL DRIVER','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0840','IC-MOTOR DRIVER','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0850','IC-RELAY DRIVER','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0860','IC-HALL EFFECT S/W','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0900','IC-FLASH MEMORY','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0910','IC-NAND FLASH','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0920','IC-MCP','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('0930','IC-MEMORY CARD','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1000','IC-AUDIO AMP','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1001','IC-POWER AMP','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1002','IC-RF AMP','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1003','IC-VOLTAGE COMP.','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1004','IC-BACKLIGHT DRIVER','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1005','IC-BATTERY','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1006','IC-DC/DC CONVERTER','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1007','IC-MULTI REG.','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1008','IC-POSI.FIXED REG.','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1009','IC-POWER SUPERVISOR','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1010','IC-RESET','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1011','IC-VOL. DETECTOR','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1012','IC-DEMODULATOR','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1013','IC-TUNER','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1014','IC-BLUETOOTH','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1015','IC-BUS TRANSCEIVER','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1016','IC-CODEC','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1017','IC-CONTROLLER','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1018','IC-EXPANDER','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1019','IC-INTERFACE','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1020','IC-LCD CONTROLLER','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1021','IC-MODEM','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1022','IC-RECEIVER','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1023','IC-SWITCH','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1024','IC-TRANSCEIVER','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1025','IC-TRANSMITTER','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1026','IC-WIFI','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1027','IC-SENSOR','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1028','Other IC','IC','IC;Function,Value,Package,Info','IC_<Part number prefix>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1810','SWITCH','SWITCH','X','SW<No of pins>_<Sub type>_<Type>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1820','PUSH-BUTTON','BUTTON','X','BTN<No of pins>_<Sub type>_<Type>');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('1900','ME-PART','ME part','X','X');
INSERT INTO `part_type` (`PREFIX`,`PART_TYPE`,`CATEGORY`,`DESCRIPTION_RULE`,`DEVICE_RULE`) VALUES ('2000','NON-STANDARD MATERIAL','NON-STANDARD MATERIAL','X','X');